#!/bin/bash
set -ex

src_dir="$(pwd)/src"
mkdir -p $src_dir

wget -O python.tar.xz "https://www.python.org/ftp/python/$PYTHON_VERSION/Python-$PYTHON_VERSION.tar.xz"
tar -xJC $src_dir --strip-components=1 -f python.tar.xz

cd $src_dir

architecture="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"

./configure \
 	--build="$architecture" \
	--prefix="$BUILD_PATH" \
 	--enable-loadable-sqlite-extensions \
 	--enable-optimizations \
 	--enable-option-checking=fatal \
 	--enable-shared \
 	--with-system-expat \
 	--with-system-ffi \
 	--without-ensurepip

make -j "$(nproc)"
make install

ldconfig $BUILD_PATH/lib
wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py
/$BUILD_PATH/bin/python3 get-pip.py
