#! /bin/bash
set -ex

dpkg_dir="$(pwd)/dpkg"
usr_dir="$dpkg_dir/usr"
debian_dir="$dpkg_dir/DEBIAN"

rm -rf $dpkg_dir
mkdir -p "$dpkg_dir" "$debian_dir" "$usr_dir"

cp -r $BUILD_PATH/* $usr_dir

cat <<EOF > $debian_dir/control
Source: https://github.com/Pythonic-Dockers/python-builder
Section: devel
Priority: optional
Maintainer: $MAINTAINER
Package: python
Version: $PYTHON_VERSION
Architecture: amd64
Depends: libbz2-1.0, libc6, libc6, libdb5.3, libexpat1, libffi6, liblzma5, libmpdec2, libncursesw5, libreadline7, libsqlite3-0, libssl1.1, libtinfo5, mime-support, mime-support, zlib1g
Pre-Depends: libc6
Description: Python $PYTHON_VERSION binaries
EOF

cat <<EOF > $debian_dir/postinst
#! /bin/sh -e

./usr/bin/python3 /usr/dpkg/pip/get-pip.py
rm -rf /usr/dpkg/pip/
EOF

chmod +x $debian_dir/postinst

wget -O $usr_dir/dpkg/pip/get-pip.py https://bootstrap.pypa.io/get-pip.py

md5deep -l -o f -r $usr_dir > $debian_dir/md5sums

dpkg-deb -b $dpkg_dir python_$PYTHON_VERSION.deb
