name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - name: Build image
      env:
        CONTAINER_IMAGE: ${{ secrets.REGISTRY_USERNAME }}/${{ github.repository }}
      run: |
        docker build . -t $CONTAINER_IMAGE
        docker push $CONTAINER_IMAGE
